### ISSUE TITLE
npm shrinkwrap

### ISSUE THREAD

**Issue by EvanHahn** [phadej/npm-freeze#2]
Pardon a stupid question: how does this differ from the `npm shrinkwrap` command?

**Comment by phadej** [comment]
It actually not stupid.
- `npm-freeze` doesn't help you install the same dependencies
- I use it to see which dependencies change when I run test suites in CI,
  - for example: https://travis-ci.org/jsverify/jsverify/jobs/78391410
- there is also branch listing licenses (but it's unmaintained)

So I build this solely out of curiosity, `npm shrinkwrap` is different.

**Comment by EvanHahn** [comment]
:+1: Thanks!
